### ISSUE TITLE
Request batching?

### ISSUE THREAD

**Issue by bnoguchi** [ekosz/redux-falcor#9]
Where does incorporating Falcor's request batching fall on redux-falcon's roadmap? In other words, letting the fetchFalcorDeps get rolled up to the root component and batched together there.

**Comment by ekosz** [comment]
Hey @bnoguchi, request batching is actually handled by `falcor`, not `redux-faclor`. For example:

```js
const falcor = new Model({ /* options */ }).batch();
```

If you then pass that model to `<FalcorProvider>` all of the requests to falcor will be batched together. Does that make sense?

**Comment by bnoguchi** [comment]
Makes sense. Any example code for how to set it up so the batched request gets sent only after it receives all requests all rendered (or about to be rendered) components' initial falcor data requests? I imagine a solution that uses a scheduler that is able to detect when all these components have registered their requests, but it seems like this would add some non trivial boilerplate code to what I'd imagine might be a popular way to want to use redux-falcor with React.

    _____________________________

**Comment by bnoguchi** [comment]
Hmm. Is the intended use of redux-falcor's reduxFalcor function to only wrap container-style components (i.e., devs shouldn't be wrapping leaf components with reduxFalcor(Leaf))? If so, that explains my confusion here. I was under the impression that I could use fetchFalcorDeps at any level of my tree of components, and I wanted to therefore roll up the requests to an ancestor component that then fired off a single batched request. But if only top-level container components are expected to fetchFalcorDeps, then I really don't need the mode of batching I was trying to explain earlier. Can you clarify on what components you intend devs to wrap with reduxFalcor(Comp)?

**Comment by jonaskello** [comment]
I think Falcor handles batching internally by having a scheduler that batches all requests it gets until the next "tick", where I think "tick" means something like a 100ms window. So that would mean that if all components are rendered within that time window, they will make separate requests in that window, but Falcor will make only one request. But that is just the impression I got from reading about Falcor, have not had any time to play with it yet so not sure. Also from what I read, Relay and om.next handles request batching differently because there the components declare their data needs and they are rolled up to one request.

**Comment by trxcllnt** [comment]
Falcor lets you pass in a custom Scheduler to the Model constructor (`new Model({ scheduler: new CustomScheduler() });` or as an [argument to the `batch` function](https://github.com/Netflix/falcor/blob/master/lib/Model.js#L447). The scheduler API is relatively straightforward; your Scheduler needs a `schedule` method that accepts a callback (and optionally returns a Disposable or function to cancel the scheduled action, if you want to support that).
